config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :price, :stock_quantity, presence: true
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.includes(:category).all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <%@products.each do |product|%>
<tr>
  <td><%= link_to product.title, product_path(product) %></td>
  <td><%= product.category.name %></td>
</tr>
<%end%>
</table>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<h2><%= @product.category.name %></h2>
<table>
  <tr>
  <td>Price: $<%= @product.price %></td>
  <td>Quantity: <%= @product.stock_quantity %></td>
  </tr>
  <tr>
    <td><%= @product.description %></td>
  </tr>
</table>

<%=link_to 'Back', products_path%>